##############################################################################
# Dockerfile to build CLARIN Dspace container images
# Based on maven:3-jdk-8
##############################################################################

# Step 1 - Run Maven Build
FROM maven:3-jdk-8 as build
WORKDIR /app

# Copy the DSpace source code into the workdir (excluding .dockerignore contents)
ADD . /app/
# Build Dspace
WORKDIR /app
RUN mvn -Dmaven.repo.local=/app/.m2/repository -T 1C clean compile
